spring.datasource.url=jdbc:mysql://localhost:3306/rfpdb
spring.datasource.username=root
spring.datasource.password= 1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=das17.shubham@gmail.com
spring.mail.password=vavi ynqu mmof tynx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

gemini.api.key=AIzaSyDdDM0t5TWpSSneifxZpxnqqZUMrzL1kYs

